### ISSUE TITLE
Support questions to be done via github issues?

### ISSUE THREAD

**Issue by noneck** [CityOfNewYork/geoclient#1]
@mlipper @colinreilly great job on getting this out the door!!

If people have questions using the geoclient, maybe they should use github issues?

Labels:
 * Inquiry
 * Bug
 * Help
 * Fix

**Comment by jqnatividad** [comment]
:+1: 

Kudos to @mlipper @colinreilly and the rest of the team!

During the Geoclient hacknight last year, I distinctly remember @mlipper mentioning looking forward to community contributions.  Using the Help tag (or in the CKAN project, they use "Good for Contributions" should help direct the energy of the civictech community towards desired features.

**Comment by mlipper** [comment]
Yup. I just added something to that effect on the README. Keep the suggestions coming! Call me at (718) 403 8094 if too much typing is involved. Thanks!

Sent from my iPhone

On Jan 12, 2016, at 10:17 AM, Noel Hidalgo <notifications@github.com<mailto:notifications@github.com>> wrote:


@mlipper<https://github.com/mlipper> @colinreilly<https://github.com/colinreilly> great job on getting this out the door!!

If people have questions using the geoclient, maybe they should use github issues?

Labels:

  *   Inquiry
  *   Bug
  *   Help
  *   Fix

�
Reply to this email directly or view it on GitHub<https://github.com/CityOfNewYork/geoclient/issues/1>.

________________________________

This e-mail, including any attachments, may be confidential, privileged or otherwise legally protected. It is intended only for the addressee. If you received this e-mail in error or from someone who was not authorized to send it to you, do not disseminate, copy or otherwise use this e-mail or its attachments. Please notify the sender immediately by replying to this e-mail and delete the e-mail from your system.

**Comment by noneck** [comment]
@mlipper awesome!

It appears that the public can only file tickets. Do you know if you can open github a bit so the public can use labels?

**Comment by mlipper** [comment]
I'm pretty sure we can in terms of "being allowed to". We're going to start by defining a core set of the standard labels and expand from there as needed.Once defined, we definitely want the public to be able to label their issues where appropriate. Does this answer your question?

In the labels you've suggested above, what's the difference between an Inquiry and Help? Similarly, between Bug and Fix?

**Comment by noneck** [comment]
Sure!

 * Inquiry / question, this is built into github's labels. 
 * Help wanted, this should be someone who needs help.
 * Bug, this is something that reports that you've found a bug. 
 * Fix, someone has a fix or code... This would work across pull requests.

have you seen [18F's guide](https://pages.18f.gov/open-source-guide/writing-clear-and-concise-issues/)?

**Comment by mlipper** [comment]
Thanks. Yes, I've seen that guide and, of course, the labels themselves are all in wide use already. My reason for asking was to focus (myself) on separating the must-have, should-have, etc. It's not that big of a deal in this context, but I'm trying to be conservative in all things relating to administrative overhead.....At least for the next couple of days, while the dust settles from the carnage of smoshing several stand-alone internal projects with independent builds into the current Franken-project.

Thanks!

**Comment by mlipper** [comment]
@noneck I'm not finding any repo settings which control the public's ability to label issues they file. I feel like I've used/seen this before but I'm not finding it now. Can you point me in the right direction?
