### ISSUE TITLE
Add Geosupport Release and Version to Response

### ISSUE THREAD

**Issue by jqnatividad** [CityOfNewYork/geoclient#13]
As DCP updates Geosupport software and data on a regular basis.

This is also related to #4.

**Comment by jqnatividad** [comment]
If adding this, also consider adding a timestamp indicating when the address was geocoded.

**Comment by mlipper** [comment]
This information is already available from the version.(json|xml) endpoint:

https://api.cityofnewyork.us/geoclient/v1/version.json

The HTML view can be found here:

https://api.cityofnewyork.us/geoclient/v1/doc#section-5.0

Neither the "doc" nor the "version" endpoints require authorization (app id's or keys).

Please let me know if this addresses your request.

**Comment by jqnatividad** [comment]
Thanks @mlipper!  However, I'm getting "Authentication parameters missing" when I tried the version endpoint.  I even tried it with my auth info (app id & key) and got the same message.

**Comment by mlipper** [comment]
I assume you're getting the same thing when opening the links above in your browser? Can you please email me privately the app_id you're trying to use?

**Comment by mlipper** [comment]
Per our discussion, access with credentials is working. I have the same issue when not providing authentication creds from home. I will talk to the NYC Developer Portal team because it looks as though a server configuration was changed.

I'm marking this as closed but creating a bug ticket for unauthenticated access. Thanks for pointing this  out!
