### ISSUE TITLE
Docker image for Geoclient

### ISSUE THREAD

**Issue by delner** [CityOfNewYork/geoclient#18]
First off, making this open source and available to the public is amazing! Thank you so much.

I'd love to deploy this on my own server for a project, as I'm sure many others would. Creating a Docker image would make it easy for others to stand up their own Geoclient quickly, without the fuss of building it themselves.

I've had some experience with Docker, and I'd be happy to help get make an image for this. But in order to do so, it'd be helpful to have a more robust list of requirements/versions as well as a list of steps to setup and start a Geoclient instance. The README in this repo is looking a little sparse right now; is there more robust documentation on the install/build/configuration/running of Geoclient?

**Comment by delner** [comment]
I did a search on DockerHub and found this image: https://hub.docker.com/r/kurtraschke/geoclient-docker/

Looks pretty promising! I'll try it out and see how it works.

**Comment by delner** [comment]
So I played around with the image, and had to roll my own with some minor alterations to get it to work with 16B. You can find the [GitHub](https://github.com/delner/geoclient-docker) and [DockerHub](https://hub.docker.com/r/delner/geoclient/) here.

For whatever reason, Geoclient is giving me back all 404s. I can't tell if its because my requests are actually 'unauthorized' or if there's genuinely something misconfigured here.

Trying `/v1/address.json?houseNumber=314&street=west%20100%20st&borough=manhattan&app_id=abc123&app_key=def456` with this bogus app key doesn't work.

The process list looks something like this right now:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  28228  7108 ?        Ss   23:25   0:00 /usr/bin/python3 -u /sbin/my_init
root         8  0.0  0.0    196    40 ?        S    23:25   0:00 /usr/bin/runsvdir -P /etc/service
root         9  0.0  0.0    176     0 ?        Ss   23:25   0:00 runsv tomcat
root        10  0.0  0.0    176     0 ?        Ss   23:25   0:00 runsv syslog-ng
root        11  0.0  0.0    176     0 ?        Ss   23:25   0:00 runsv cron
root        12  0.0  0.0    176     4 ?        Ss   23:25   0:00 runsv syslog-forwarder
root        13  0.0  0.0    176     0 ?        Ss   23:25   0:00 runsv sshd
root        14  0.0  0.0  63668  6236 ?        S    23:25   0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
root        15  3.8  6.3 4504080 512800 ?      Sl   23:25   0:28 java -Djava.library.path=/app/version-16b_16.2/lib/:/app/geoclient/buil
root        16  0.0  0.0  26748  2588 ?        S    23:25   0:00 /usr/sbin/cron -f
root        19  0.0  0.0   7480   688 ?        S    23:25   0:00 tail -F -n 0 /var/log/syslog
root        54  0.0  0.0  18144  3340 ?        Ss   23:27   0:00 /bin/bash
root        71  0.0  0.0  15568  2192 ?        R+   23:38   0:00 ps aux
```

Any ideas why the service is throwing 404s?

**Comment by mlipper** [comment]
I won't be able to properly address all of your questions, requests, and suggestions until (hopefully) sometime tomorrow. In the meantime, here are a few shots in the dark that may keep you moving forward:

- Given that the 404 is coming from your vm's Tomcat, the first thing to check is whether you've deployed the geoclient-service-2.0.0-SNAPSHOT.war using the default Servlet context name assigned by Tomcat in absence of more specific configuration (`context.xml` I think). As with many Servlet containers, Tomcat assigns the context (URI) by using the war file's name. e.g., check `http://localhost:8080/geoclient-service-2.0.0-SNAPSHOT/address.json?etc...` Obviously, protocol, host and port should be adjusted as needed.

- Check the logs for what Tomcat thinks is happening. Depending on how Tomcat's installed, there are a default location(s) the server might be writing them. Usually, the environment variables `CATALINA_HOME` and `CATALINA_BASE` will have a subdirectory called "logs". In the vanilla Apache download, the two variables point to the same directory. Check the Tomcat docs and look at:
  
  1. Access log to verify that your calls are reaching the right server/instance.
  2. Catalina server log(s) to grep for the HTTP path to which the geoclient-service application was published.
  3. Catalina "out" or "error" log(s) to see if Geoclient choked (most likely because of `java.library.path` and/or `LD_LIBRARY_PATH` not properly set in the `CATALINA_BASE/bin/env.sh` script).

- I've only had time to glance at your repo and Docker configuration files, but I noticed you're using the `dev` branch. Try using `master` instead: I merged a bunch of native fixes from the `jni` branch today and fixed some broken logic in the Gradle build. (I recently added a warning to the `README.md` against depending on branches other than `master` right now, but as you've mentioned, the documentation needs improvement badly).

HTH for now. Tomorrow I'll try to provide more answers. 

Thanks for your interest in Geoclient!
Matt

**Comment by delner** [comment]
Okay, I'll take a look at this. In the mean time, I'll leave my Dockerfile here, which explains how this Geoclient was setup. Is there any glaring omission that you see?

```
FROM phusion/baseimage:0.9.18

CMD ["/sbin/my_init"]

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends wget unzip git openjdk-7-jdk maven build-essential

RUN mkdir /app/

WORKDIR /app/

RUN wget http://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/gdelx16b.zip \
    && unzip gdelx16b.zip \
    && rm gdelx16b.zip

ENV GEOSUPPORT_HOME=/app/version-16b_16.2 \
    JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/
ENV LD_LIBRARY_PATH=$GEOSUPPORT_HOME/lib/ \
    GEOFILES=$GEOSUPPORT_HOME/fls/ \
    GS_INCLUDE_PATH=$GEOSUPPORT_HOME/include/foruser \
    GS_LIBRARY_PATH=$GEOSUPPORT_HOME/lib


RUN git clone https://github.com/bhagyas/spring-jsonp-support \
    && ( cd spring-jsonp-support \
         && mvn -Dmaven.compiler.source=1.7 -Dmaven.compiler.target=1.7 install ) \
    && rm -rf spring-jsonp-support

COPY geoclient-build.patch .

RUN git clone https://github.com/CityOfNewYork/geoclient.git \
    && ( cd geoclient \
         && git checkout dev \
         && patch -p1 < /app/geoclient-build.patch \
         && ./gradlew build -x test )

RUN wget http://central.maven.org/maven2/com/github/jsimone/webapp-runner/7.0.57.2/webapp-runner-7.0.57.2.jar

RUN DEBIAN_FRONTEND=noninteractive apt-get remove -y unzip wget git openjdk-7-jdk maven build-essential \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends openjdk-7-jre-headless \
    && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.m2 root/.gradle

RUN mkdir /etc/service/tomcat
ADD tomcat.sh /etc/service/tomcat/run
RUN chmod +x /etc/service/tomcat/run
```

**Comment by mlipper** [comment]
Regarding the Dockerfile:

- You're using OpenJDK's JDK instead of Oracle's semi-proprietary JDK. I've built and run Geoclient on openjdk-7-jdk successfully and I think it's important that geoclient run easily on a fully Open Source runtime. However, geoclient was originally written and tested against the Oracle 7 and 8 JDK's. I've added #19.

- Your Dockerfile references `openjdk-7-jre-headless`. If you experience runtime issues, consider configuring Tomcat to use a JDK and not just a JRE. 

- You are relying on the `dev` branch which is ok right now but is often unstable and is not safe for forking (see 94ea6c4570feba5c4ecfb7e89939f4964e59da5b).

**Comment by delner** [comment]
Although I've done some Java programming before, and a lot of other web servers (Ruby/C#), I'm not familiar with Java + Tomcat, so I apologize in advance if I seem to be missing some obvious things here. I'm basing most of what I'm doing here off of Kurt's work, and I'm trying to catch up and understand how things are being setup & configured.

I tried to follow some of your advice here, and I'll try to catch you up on what's happening in my Docker container. Although I still am using OpenJDK, I started off by swapping `dev` for `master`, and adjusted the patch I was applying to the Geoclient to look like this:

```
diff --git a/build.gradle b/build.gradle
index 6285bf3..3ff03b2 100644
--- a/build.gradle
+++ b/build.gradle
@@ -20,7 +20,9 @@ allprojects {
   version = rootProject.version
 
   repositories {
+    maven { url "http://maven.geotoolkit.org/" }
     jcenter()
+    mavenLocal()
     mavenCentral()
   }

diff --git a/geoclient-native/build.gradle b/geoclient-native/build.gradle
index a53dde0..757a8ae 100644
--- a/geoclient-native/build.gradle
+++ b/geoclient-native/build.gradle
@@ -64,7 +64,7 @@ model {
           cCompiler.define "DLL_IMPORT"
           linker.args "-L${gsLibraryPath}", "-lm", "-lNYCgeo", "-lgeo", "-ledequiv", "-lapequiv", "-lsan", "-lsnd", "-lstExcpt", "-lStdLast", "-lStdUniv", "-lstEnder", "-lstretch", "-lthined"
         } else if (targetPlatform.operatingSystem.linux) {
-          linker.args "-L${gsLibraryPath}", "-lc", "-lm", "-lgeo", "-ledequiv", "-lapequiv", "-lsan", "-lsnd", "-lstExcpt", "-lStdLast", "-lStdUniv", "-lstEnder", "-lstretch", "-lthined"
+          linker.args "-Wl,--no-as-needed", "-L${gsLibraryPath}", "-lc", "-lgeo", "-lm", "-ledequiv", "-lapequiv", "-lsan", "-lsnd", "-lstExcpt", "-lStdLast", "-lStdUniv", "-lstEnder", "-lstretch", "-lthined"
         }
       }
     }
```

This appears to patch and build successfully in my Docker container. Here's what my `/app/` folder looks like:

```
root@a5416a39c93b:/app# ls
geoclient  geoclient-build.patch  version-16b_16.2  webapp-runner-7.0.57.2.jar
```
`geoclient` is the Geoclient git repo, and `version-16b_16.2` is the folder of the extracted Geosupport. It looks like the compiled Geoclient service ended up in `/app/geoclient/geoclient-service/build/libs/geoclient-service-2.0.0-SNAPSHOT.war`.

Now this is the part I start to get a little fuzzy. I started by looking for those `CATALINA` environment variables you mentioned, but neither of those are set. Yet curiously it seems like Tomcat is running since the 404s come back from a server tagging the responses with "Apache Tomcat/7.0.57".

It looks like there's a script `/etc/service/tomcat/run` which has the following content:

```
#!/bin/sh
exec java -Djava.library.path=$LD_LIBRARY_PATH:/app/geoclient/build/libs/ \
     -jar /app/webapp-runner-7.0.57.2.jar \
     /app/geoclient/geoclient-service/build/libs/geoclient-service-2.0.0-SNAPSHOT.war \
     >> /var/log/tomcat.log 2>&1
```

Looking at `ps aux`, it seems to be running:

```
root@a5416a39c93b:/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.4  28228  9432 ?        Ss   17:21   0:00 /usr/bin/python3 -u /sbin/my_init
root         9  0.0  0.0    196    40 ?        S    17:21   0:00 /usr/bin/runsvdir -P /etc/service
root        10  0.0  0.0    176     4 ?        Ss   17:21   0:00 runsv tomcat
root        11  0.0  0.0    176     4 ?        Ss   17:21   0:00 runsv cron
root        12  0.0  0.0    176     4 ?        Ss   17:21   0:00 runsv syslog-ng
root        13  0.0  0.0    176     4 ?        Ss   17:21   0:00 runsv syslog-forwarder
root        14  0.0  0.0    176     4 ?        Ss   17:21   0:00 runsv sshd
root        15  1.4 22.1 2860112 453356 ?      Sl   17:21   0:22 java -Djava.library.path=/app/version-16b_16.2/lib/:/app/geoclient/build/libs/ -jar /app/web
root        16  0.0  0.3  63672  6660 ?        S    17:21   0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
root        17  0.0  0.1  26748  2604 ?        S    17:21   0:00 /usr/sbin/cron -f
root        19  0.0  0.0   7480   724 ?        S    17:21   0:00 tail -F -n 0 /var/log/syslog
root        47  0.0  0.1  18148  3252 ?        Ss   17:23   0:00 /bin/bash
```

That script seems to be piping output to `/var/log/tomcat.log`. Opening it up, here's what I found:

```
root@1d048b436915:/app# cat /var/log/tomcat.log 
Adding Context  for /app/geoclient/geoclient-service/build/libs/geoclient-service-2.0.0-SNAPSHOT.war
Jun 30, 2016 5:50:54 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Jun 30, 2016 5:50:55 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jun 30, 2016 5:50:55 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Jun 30, 2016 5:50:55 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.57
Jun 30, 2016 5:50:55 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Jun 30, 2016 5:50:57 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [ch/qos/logback/core/util/EnvUtil.class] from Jar [jar:jndi:/localhost/WEB-INF/lib/logback-core-1.1.5.jar!/] for annotations
java.io.EOFException
	at org.apache.tomcat.util.bcel.classfile.FastDataInputStream.readInt(FastDataInputStream.java:145)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readID(ClassParser.java:200)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:78)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2071)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1947)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1913)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1898)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5380)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Jun 30, 2016 5:50:57 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [org/apache/commons/beanutils/BasicDynaClass.class] from Jar [jar:jndi:/localhost/WEB-INF/lib/commons-beanutils-1.8.3.jar!/] for annotations
java.io.EOFException
	at org.apache.tomcat.util.bcel.classfile.FastDataInputStream.readInt(FastDataInputStream.java:145)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readID(ClassParser.java:200)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:78)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2071)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1947)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1913)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1898)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5380)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Jun 30, 2016 5:50:58 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [org/unbescape/uri/UriEscapeUtil$1.class] from Jar [jar:jndi:/localhost/WEB-INF/lib/unbescape-1.1.0.RELEASE.jar!/] for annotations
java.io.EOFException
	at org.apache.tomcat.util.bcel.classfile.FastDataInputStream.readInt(FastDataInputStream.java:145)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readID(ClassParser.java:200)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:78)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2071)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1947)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1913)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1898)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5380)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Jun 30, 2016 5:51:00 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jun 30, 2016 5:51:00 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
17:51:01.669 [localhost-startStop-1] INFO  WebConfig   - ===[StandardServletEnvironment {activeProfiles=[], defaultProfiles=[default], propertySources=[servletConfigInitParams,servletContextInitParams,systemProperties,systemEnvironment,class path resource [version.properties]]}]===
17:51:02.284 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=HR, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_HR, length=5026, isWorkAreaOne=false]]
17:51:02.315 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=1, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F1, length=300, isWorkAreaOne=false]]
17:51:02.335 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=1E, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F1, length=300, isWorkAreaOne=false]]
17:51:02.346 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=1A, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F1A, length=1363, isWorkAreaOne=false]]
17:51:02.369 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=1AX, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F1AX, length=2800, isWorkAreaOne=false]]
17:51:02.389 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=1B, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F1B, length=4300, isWorkAreaOne=false]]
17:51:02.411 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=BL, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F1AX, length=2800, isWorkAreaOne=false]]
17:51:02.418 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=BN, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F1AX, length=2800, isWorkAreaOne=false]]
17:51:02.424 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=2, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F2, length=200, isWorkAreaOne=false]]
17:51:02.426 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=3, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=WorkAreaConfig [id=WA2_F3, length=1000, isWorkAreaOne=false]]
17:51:02.430 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=DG, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=null]
17:51:02.431 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=BF, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=null]
17:51:02.431 [localhost-startStop-1] INFO  GeosupportConfig - Creating function from FunctionConfig [id=BB, workAreaOne=WorkAreaConfig [id=WA1, length=1200, isWorkAreaOne=true], workAreaTwo=null]
Jun 30, 2016 5:51:03 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'appServlet'
Jun 30, 2016 5:51:03 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
```

Those exceptions look pretty nasty to me, but I'm not sure if they're fatal... any thoughts here? The script looks like it should be mounting the Geoclient servlet by way of `webapp-runner` which appears to be some small Tomcat package?

**Comment by delner** [comment]
You know what... strike all that... calling `http://localhost/address.json?houseNumber=314&street=west%20100%20st&borough=manhattan` yielded:

```
{"address": {...}}
```

...which looks like success to me! I'll push this Docker image up to [my DockerHub repo](https://hub.docker.com/r/delner/geoclient/) and update my [Github repo](https://github.com/delner/geoclient-docker) as well.

It sounds like you already recommended switching to Oracle JDK for now, but if I were to try to make this service "production ready", are there any other recommended changes you'd suggest here? Performance related or otherwise?

**Comment by mlipper** [comment]
Here are some recommendations. Some of them have nothing to do with Geoclient and simply reflect my personal preferences based on my experience:

- I would not ignore the Tomcat server startup errors (which look like they come from an incompatibility between your JVM (JDK or JRE) and a jar that's presumably part of the webapp-runner utility.These stacktraces usually indicate a mismatch between minor version support for fundamental Java language features (Annotations in this case).

- Unless you have some specific reason to use the webapp-runner utility, I recommend just using  Tomcat directly. Especially if this extra library obscures the "well-known" Tomcat configuration and monitoring mechanisms AND it has serious startup errors on day one. It might require an hour or two of skimming the Tomcat configuration docs (or the webapp-runner docs) but you probably should do that anyway before making this part of a production deployment.

- Plan for upcoming Geoclient Java 1.8 support and parameterize accordingly. Geoclient v2.x will support both a 1.7 and 1.8 runtime. In the not-too-distant future, it's likely that the build will require 1.8.

- I'm not sure why the `geoclient-native` build required the addition of that linker flag (`-Wl,--no-as-needed`). IIRC, that flag is essentially a workaround for pthread issues on only certain Linux distributions. I think a better approach might be to insure that `g++` and `openjdk-7-jdk` and/or `openjdk-8-jdk` are already installed and try removing this from the patch. That same line also reverses the order of libm and libgeo (`"-lgeo", "-lm"`). That may be valid for you build but if it's just a typo, I'd take it out of the patch.

- Speaking for myself, I would not have my production application depend on anything that had undiagnosed errors as seen above without a better understanding of the risk I was taking or -- at the very least -- a basic understanding of how to troubleshoot the server runtime.

- Finally, I try to avoid production builds that rely on snapshot components because it makes versioning your own build questionable and, depending on the situation, even non-repeatable. To mitigate this risk, I suggest setting up a good CI pipeline dedicated to load and functional testing in the context of your application's needs.

**Comment by delner** [comment]
Cool. I figured since you know this service well, you'd best know it's limitations or optimal configuration for it. These recommendations do make a lot of sense, so thank you for them.

**Comment by delner** [comment]
Okay, made some more progress.

 - Rebased the Docker image on top of Tomcat 7.0.70
 - Removed webapp-runner.jar
 - Those startup errors are gone.
 - Reorded the `-lm -lgeo` flags.

Some thing that could use more work...

 - Switch to OpenJDK Java 8. I held off on this for now because it doesn't sound fully supported yet. From what little research I was doing, it seems like because this is running in Docker, Oracle JDK is a no go.
 - Tried to remove `-Wl,--no-as-needed` flag to eliminate the need for patching, but compiling geoclient-native failed when doing so. Kept it for now until we can solve the mystery. It'd be wonderful if we could eliminate the patch in the future.
 - Using default Tomcat logging right now. Could use a more sophisticated setup for this in the future.

I can see the argument for not using SNAPSHOT WARs to base these images on. I think I'd prefer using a versioned WAR, but are these already available somewhere? A CI pipeline for Geoclient that could generate these sounds wonderful, but its not something I have the resources to manage.

In the absence of that, I think I might have to stick to compiling from source at the moment. At least these Docker images will allow others to use Geoclient binaries without having to compile it themselves, which hopefully reduces inconsistent behavior. But yeah, there aren't really guarantees if someone builds this image themselves...

**Comment by mattkime** [comment]
@delner we may have similar interests, i may be interested in helping out

**Comment by mlipper** [comment]
@mattkime , @delner
I'm happy to help out as well, time permitting. Ultimately, I'd like to have an "examples" subproject with different recipes for running Geoclient on different platforms/build environments/containers/languages, etc.

@delner, 
I've made some progress on building/running the project on openjdk and/or Java 8 . I've been working on other stuff recently, but I'll try to refresh my memory on the gcc compiler switch issue (IIRC, it turned out to be related to a bug in my Gradle build which misidentified the platform and hosed the linker arguments). 

I'm not sure I understand the Tomcat logging issue. Could you provide more details?

I'm a little crunched for time right now, but I'll checkout your latest updates and see if I can provide more specific answers.

**Comment by delner** [comment]
@mattkime Glad to have you on board!

@mlipper Nice to hear it's almost on Java 8. As new versions of Geosupport come out, I'll continue to update the existing Docker image. When it's ready for Java 8, we can do that switch over.

I think the logging is working OK as far as default Tomcat logging goes. I guess my comment was alluding to maybe the Docker image should be modified to surface those log files in a way that enterprise systems could ingest them more easily into their own monitoring systems (e.g. Logstash/ElasticSearch/Kibana.)

But perhaps that's out of scope here, and we should leave to other developers to build such features upon the existing image, so I wouldn't worry too much about that one. Sounds like you have bigger fish to fry anyways!

**Comment by mlipper** [comment]
I hope to link to your repos and/or provide some example configurations/repos of my own once I'm more familiar with Docker.

I'm happy to contribute to existing efforts but I may also start from scratch because my use cases seem to require a more general scope. 

I'm closing this thread for now. Please feel free to re-open or re-create as needed.

Thanks everyone!

**Comment by delner** [comment]
For sure. I'd love to see a generalized 'official' Docker repo whenever that happens. Feel free to pick mine apart, or ask any questions.
