### ISSUE TITLE
Java compilation error with latest master

### ISSUE THREAD

**Issue by chrismarx** [CityOfNewYork/geoclient#24]
Building the geoclient-service module now fails with:

/home/geoclient/git/geoclient/geoclient-service/src/main/java/gov/nyc/doitt/gis/geoclient/service/web/RestController.java:47: error: annotation CrossOrigin is missing value for the attribute <clinit>
@CrossOrigin
^
/home/geoclient/git/geoclient/geoclient-service/src/main/java/gov/nyc/doitt/gis/geoclient/service/search/web/SingleFieldSearchController.java:34: error: annotation CrossOrigin is missing value for the attribute <clinit>
@CrossOrigin

This appears to be a problem that is fixed only in the very most recent version of the java jdk, this post had an answer:

We faced the same issue. When using eclipse compiler to build your project (ejc) it works fine, but does NOT compile at all with javac. This is a known and resolved issue in java 1.8 and has been back-ported to java 7. So, Update to the latest java 7 version (7u80) or Java 8 version.
Here is the bug:
https://bugs.openjdk.java.net/browse/JDK-8013485

https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

Upgrading did fix the compilation problem, but this has to be included in the build instructions-

PS - Or should we be building with a java 8 jdk at this point?

**Comment by mlipper** [comment]
Hi Chris,

Thanks for pointing this out. I will update the docs with this information as soon as I can. Recently, I've been busy with other stuff.

BTW, to maximize the visibility of your contributions, I'm always happy to:

- Make the updates myself on a temporary branch which you can use to fast-forward your local master and then submit as a standard pull request.
- Accept a standard pull request from you (if necessary, after working out questions, implementation details, etc.)
- Any other ideas you have...

Thanks and please keep 'em coming!

**Comment by chrismarx** [comment]
Ok, 

I've got one more. The build completed. The war file deployed without issue on tomcat. But going to this url:

http://localhost:8080/geoclient/address.json?houseNumber=....

returns:

'''
{"address":{"crossStreetNamesFlagIn":"E","firstBoroughName":"QUEENS","firstStreetCode":"44589001010","firstStreetNameNormalized":"FRANCIS LEWIS BOULEVARD","geosupportFunctionCode":"1B","geosupportReturnCode":"67","geosupportReturnCode2":"67","houseNumber":"37-14","houseNumberIn":"37-14","houseNumberSortFormat":"100037014AA","message":"ERROR ACCESSING GEOSUPPORT FILE: GRID1. NOTIFY SYSTEM SUPPORT","message2":"ERROR ACCESSING GEOSUPPORT FILE: UPAD. NOTIFY SYSTEM SUPPORT","reasonCode":"G","reasonCode1a":"P","reasonCode1e":"G","reasonCode2":"P","returnCode1a":"67","returnCode1e":"67","streetName1In":"FRANCIS LEWIS BLVD","workAreaFormatIndicatorIn":"C","zipCodeIn":"11362"}}
'''

**Comment by mlipper** [comment]
Hi Chris,

I'm sorry for the delay in getting back to you. This response indicates a few things:

  1. The JNI stuff is setup correctly. 

I know this because the Java <--> C class/library path loading happens on JVM startup when the Classloader loads `gov.nyc.doitt.gis.geoclient.jni.GeoclientImpl` class (that class defines the native method for accessing the Geosupport C API). In other words, the response above is coming from a running instance of the app and not from standard error.

  2. Geosupport can't find its data files. 
      
**Solution:** make sure the `GEOFILES` env variable points to the `<geosupport_install>/fls/` directory and that _the last character is (on Linux) a forward slash_.

The `message` and `message2` attributes indicate that Geosupport doesn't know where to find its lookup data. This location is defined by an environment variable called `GEOFILES` which must be visible to the JVM process. When running in Tomcat, the standard way to export environment variables is to create an OS-specific shell script called setenv.sh, setenv.bat, etc... and place it in the `$CATALINA_BASE/bin` or a `$CATALINA_HOME/bin` directory.

I can't be 100% sure this is your issue but, given that I always forget about this puzzling `GEOFILES` configuration requirement, I'm feeling lucky this time.

Please let me know how it turns out,

Matt

**Comment by chrismarx** [comment]
Oh, thank you thank you, you're absolutely correct. In my new setup, I added a startup script using initctl, and I had to set the LD_LIBRARY_PATH in the script itself, but I neglected to add the other environmental variables. 

One other note, I see that the dependencies on jai_core were commented out in the build.gradle file from geoclient-service, and that does indeed let the build complete, but then during runtime, I got errors about missing classes that were from the jair_core jar. I ended just adding the jar directly to the deployment folder in tomcat, and everything started working-

**Comment by mlipper** [comment]
This was (hopefully) fixed on branch 'build' in commit 62c22d33704ebff23b944613a9c9c2e8372b8687. Can you checkout the build branch and try again (make sure to save any unversioned working directory changes  first or just clone to a different directory)?

**Comment by WesRentlogic** [comment]
Thanks guys!
Adding GEOFILES to setenv.sh in Tomcat solved my problem.

**Comment by mlipper** [comment]
Good to hear. I'm closing this ticket but please feel free to re-open if necessary
