### ISSUE TITLE
Results differ between Single Field Search and Address endpoints

### ISSUE THREAD

**Issue by chriszrc** [CityOfNewYork/geoclient#25]
Perhaps this is expected behavior, but I get different results from these two endpoints with the same address:

`https://api.cityofnewyork.us/geoclient/v1/address.json?houseNumber=219-15&street=130%20Dr&borough=queens`

and

`https://api.cityofnewyork.us/geoclient/v1/search.json?input=219-15%20130%20Dr%20Laurelton`

Interestingly, if I try the sfs like this:

`https://api.cityofnewyork.us/geoclient/v1/search.json?input=219-15%20130%20Dr%20Queens`

It does work. The api docs says:

> If the input string ends with a known N.Y.C. city name it is removed and kept as a <CITY_NAME> token:

So I would think this would work?
Thanks!

**Comment by mlipper** [comment]
This does seem to be a bug and I'll toss it on the pile. Taking a wild guess, the issue likely stems from the fact that the /search endpoint uses static data to map a finite set of city names to one of the five boroughs needed when calling Geosupport. 

The single-field search capability is currently the only Geoclient feature that uses logic and data from outside of the Geosupport application/dataset itself. This feature was one of the reasons this project was originally created and it can be very helpful; the downside is that it relies on arbitrary external data that is not nearly as complete or accurate as what's built into Geosupport itself.

I can't provide an ETA for the fix until I investigate, but please continue to filing reports if you find other such issues.

Thank you for bringing this to our attention!

**Comment by chriszrc** [comment]
Ok,

Thanks for explaining. So in general though then, since the city name isn't even required to use the /address endpoint, is providing just the address and the borough to the /search endpoint sufficient enough to get accurate geocoding? It would seem like it is?

Thanks!

**Comment by mlipper** [comment]
For all calls, it is always better to provide the borough if available. This is because all the supported Geosupport functions require a borough (address calls will accept either a borough or zip code). Similarly, when using the single-field search (SFS) API, providing the borough is always preferable because then Geoclient doesn't have to try to "guess" which borough to use; in this case, translating the city name "Laurelton" to the standard (to Geosupport) borough name "Queens".

The /search endpoint was created because for, e.g., user-driven searches from a web app or when geocoding a third-party dataset such information often isn't known or doesn't exist. The SFS functionality provides it's own free-form, NYC-specific location parser, fuzzy search and (limited) data-cross-referencing. It provides a limited degree of client-specified algorithm configuration and recursive search based of suggestions returned by Geosupport for unrecognized locations. However, these features come at the price of reduced accuracy because they rely on Geoclient-only logic/heuristics for parsing and interpreting the intended target of your search.

As an imperfect analogy, consider the difference between searching Google and the IMDb for a particular film. The former is great when you're not really sure of the movie's name but the latter is always more conclusive, if you know the name, director, year of release, etc.

Does that make sense or did I just make this more confusing?

**Comment by chriszrc** [comment]
Yes, makes perfect sense, thanks! In our case we always know the borough, so this works out great for us-

**Comment by mlipper** [comment]
I'm closing this ticket for now; please reopen or create a new ticket as needed. Thanks, Matt
