### ISSUE TITLE
CitySDK module support

### ISSUE THREAD

**Issue by jqnatividad** [CityOfNewYork/geoclient#5]
As per @technickle

https://talk.beta.nyc/t/geoclient-is-now-open-source/1857/3

**Comment by mlipper** [comment]
Perhaps I'm missing something but this seems like a feature request that should be made to the CitySDK team?

**Comment by jqnatividad** [comment]
IMHO, I think this is one of the low-hanging fruits that will greatly enhance Geoclient in two distinct ways.  

* by creating a Geoclient module, CitySDK users can get NYC-specific data to supplement the rich demographic data that [CitySDK offers](https://uscensusbureau.github.io/citysdk/whatsinthecensusapi.html).  As CitySDK adoption accelerates, tools/apps that use it can readily be adapted to NYC.

* this can also be an opportunity to improve Geoclient itself. Right now, Geoclient already returns Census data (block/tract for past decennial census going back to 1990) from Geosupport.  What if Geoclient uses CitySDK as a passthrough module?  That is, beyond returning Geosupport info, API results can be further enriched with CitySDK data for the location?  Users will still have to get a Census API Key, but it will save Geoclient users the additional step of integrating CitySDK.  
As you mentioned, Geoclient is a thin wrapper around Geosupport.  What if, it can also be used as a way to enrich Geosupport data with location data from 3rd-party APIs by supporting modules?

**Comment by mlipper** [comment]
IMO, Geoclient is already a larger code base then it should be given its goal; for now, rather than broadening its scope, we're focusing on making it easier to use, re-use and maintain. Sticking to the Unix philosophy of having lots of tools that each do one or two things well but easily work together allows a project like this to provide the most benefit.

In any case, our opinionated approach doesn't hold you back in any way: stick a fork in it!

**Comment by jqnatividad** [comment]
Exactly!  :smile:
