### ISSUE TITLE
Migrate Documentation to ReadTheDocs

### ISSUE THREAD

**Issue by jqnatividad** [CityOfNewYork/geoclient#9]
Right now, its maintained here - https://api.cityofnewyork.us/geoclient/v1/doc

As the community contributes to the project, that will necessarily require contributing documentation changes in their PRs, and the docs be in GH.

I'm guessing this is in the v2.0 reorg?

**Comment by mlipper** [comment]
The docs are there because the geoclient web app itself also serves HTML mediaTypes in addition to JSON and XML: i.e., originally, Geoclient auto-generated a base set of static files by parsing the Geosupport Uinversal Programming Guide and spitting it out as HTML. I added some stuff for the GC single field search functionality which is not built into GS. Version information content dynamic and comes from calling the built-in "/version.[json|xml]" endpoint.

For 2.0, we were thinking about getting rid of most of this since the bulk of it is just the documentation for Geosupport itself. As such, it is slightly out-of-date and, unless we can work with DCP to come up with an automated feed/pipeline of their docs, will always be that way.

We were discussing whether to replace it with some lightweight swagger-generated forms to allow people to submit test requests interactively and then add links to DCP once their HTML version is available on the web. We'd still supply GC version info and document GC service endpoints.

What do you think?

**Comment by jqnatividad** [comment]
Oh cool! Swagger is even better!

**Comment by mlipper** [comment]
Please see #11 and #12 which are related to this issue
